# A sample Gemfile
source "https://rubygems.org"
ruby "2.2.0"

gem "sinatra", :github => "sinatra/sinatra"
gem "sinatra-contrib", :github => "sinatra/sinatra-contrib"
gem "tilt"
gem "haml"
gem "parallel", :github => "grosser/parallel"
gem "unirest"
